# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Lily58 OLED Display
# CONFIG_ZMK_DISPLAY=y

# Save the QWERTY/Colemak/Dvorak selection made on Adjust to flash.
CONFIG_ZMK_BEHAVIOR_PDF=y
