manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: chazrowe
      url-base: https://github.com/ChazRowe
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-persistent-default-layer
      remote: chazrowe
      revision: 5a0cfa8623fbe005d39c94192a6b5cf969856725
  self:
    path: config
